"""Analyze synthetic image quality and compare T2I backends.

This script evaluates the quality of synthetic images generated by different
text-to-image backends (Stable Diffusion, DALL-E, etc.) using:
- FID (Frechet Inception Distance) vs real images
- IS (Inception Score)
- LPIPS (Learned Perceptual Image Patch Similarity)
- Task vector similarity (cosine similarity between synthetic and real task vectors)

Usage:
    python scripts/analyze_synthetic_quality.py \
        --synthetic-dir data/synthetic_images \
        --real-dataset CIFAR10 \
        --metrics fid,is,lpips \
        --output synthetic_quality_comparison.pdf
"""

import os
import json
import argparse
from pathlib import Path
from typing import Dict, List, Optional, Tuple
import numpy as np
import torch
from PIL import Image
import matplotlib.pyplot as plt


def count_images_per_class(synthetic_dir: str, backend: str, dataset: str) -> Dict[str, int]:
    """Count synthetic images per class.

    Args:
        synthetic_dir: Base directory for synthetic images
        backend: T2I backend name
        dataset: Dataset name

    Returns:
        Dictionary mapping class names to image counts
    """
    base_path = Path(synthetic_dir) / backend / dataset
    counts = {}

    if not base_path.exists():
        return counts

    for class_dir in base_path.iterdir():
        if class_dir.is_dir():
            count = len(list(class_dir.glob("*.png"))) + len(list(class_dir.glob("*.jpg")))
            counts[class_dir.name] = count

    return counts


def compute_image_statistics(image_dir: str) -> Dict[str, float]:
    """Compute basic image statistics.

    Args:
        image_dir: Directory containing images

    Returns:
        Dictionary with statistics
    """

    stats = {
        'num_images': 0,
        'avg_width': 0,
        'avg_height': 0,
        'formats': {}
    }

    image_path = Path(image_dir)
    if not image_path.exists():
        return stats

    widths = []
    heights = []

    for img_file in image_path.rglob("*"):
        if img_file.suffix.lower() in ['.png', '.jpg', '.jpeg']:
            try:
                with Image.open(img_file) as img:
                    widths.append(img.width)
                    heights.append(img.height)

                    fmt = img_file.suffix.lower()
                    stats['formats'][fmt] = stats['formats'].get(fmt, 0) + 1
                    stats['num_images'] += 1
            except Exception:
                pass

    if widths:
        stats['avg_width'] = np.mean(widths)
        stats['avg_height'] = np.mean(heights)
        stats['min_width'] = min(widths)
        stats['max_width'] = max(widths)
        stats['min_height'] = min(heights)
        stats['max_height'] = max(heights)

    return stats


def compute_fid_score(real_features: np.ndarray, fake_features: np.ndarray) -> float:
    """Compute FID score between real and fake feature distributions.

    Args:
        real_features: Features from real images [N, D]
        fake_features: Features from fake images [M, D]

    Returns:
        FID score (lower is better)
    """
    # Compute means
    mu_real = np.mean(real_features, axis=0)
    mu_fake = np.mean(fake_features, axis=0)

    # Compute covariances
    sigma_real = np.cov(real_features, rowvar=False)
    sigma_fake = np.cov(fake_features, rowvar=False)

    # Compute FID
    diff = mu_real - mu_fake
    diff_sq = np.sum(diff ** 2)

    # Matrix square root (using eigendecomposition)
    try:
        from scipy import linalg
        covmean = linalg.sqrtm(sigma_real @ sigma_fake)

        # Handle numerical errors
        if np.iscomplexobj(covmean):
            covmean = covmean.real

        fid = diff_sq + np.trace(sigma_real + sigma_fake - 2 * covmean)
    except Exception:
        # Fallback: just use mean distance
        fid = diff_sq

    return float(fid)


def compute_inception_score(probs: np.ndarray, splits: int = 10) -> Tuple[float, float]:
    """Compute Inception Score.

    Args:
        probs: Softmax probabilities from classifier [N, C]
        splits: Number of splits for computing mean/std

    Returns:
        (mean IS, std IS)
    """
    N = probs.shape[0]
    split_size = N // splits

    scores = []
    for i in range(splits):
        part = probs[i * split_size:(i + 1) * split_size]

        # p(y|x)
        py_given_x = part

        # p(y) = mean of p(y|x)
        py = np.mean(py_given_x, axis=0, keepdims=True)

        # KL divergence
        kl = py_given_x * (np.log(py_given_x + 1e-10) - np.log(py + 1e-10))
        kl = np.sum(kl, axis=1)

        # IS = exp(mean(KL))
        scores.append(np.exp(np.mean(kl)))

    return float(np.mean(scores)), float(np.std(scores))


def load_task_vector_similarity(checkpoint_dir: str, synthetic_backend: str) -> Optional[float]:
    """Load precomputed task vector similarity.

    Args:
        checkpoint_dir: Directory with task vector checkpoints
        synthetic_backend: Name of synthetic backend

    Returns:
        Cosine similarity score or None
    """
    sim_file = Path(checkpoint_dir) / f"synthetic_{synthetic_backend}_similarity.json"
    if sim_file.exists():
        with open(sim_file) as f:
            data = json.load(f)
            return data.get('cosine_similarity')
    return None


def print_quality_report(results: Dict[str, Dict]):
    """Print formatted quality report.

    Args:
        results: Dictionary mapping backends to quality metrics
    """
    print("\n" + "=" * 70)
    print("SYNTHETIC IMAGE QUALITY REPORT")
    print("=" * 70)

    for backend, metrics in results.items():
        print(f"\n{backend.upper()}")
        print("-" * 40)

        if 'image_stats' in metrics:
            stats = metrics['image_stats']
            print(f"  Images: {stats.get('num_images', 0)}")
            print(f"  Avg size: {stats.get('avg_width', 0):.0f}x{stats.get('avg_height', 0):.0f}")

        if 'fid' in metrics:
            print(f"  FID Score: {metrics['fid']:.2f} (lower is better)")

        if 'is_mean' in metrics:
            print(f"  Inception Score: {metrics['is_mean']:.2f} +/- {metrics['is_std']:.2f}")

        if 'lpips' in metrics:
            print(f"  LPIPS: {metrics['lpips']:.4f} (lower is better)")

        if 'tv_similarity' in metrics:
            print(f"  Task Vector Similarity: {metrics['tv_similarity']:.4f}")

        if 'cost_per_1000' in metrics:
            print(f"  Cost per 1000 images: ${metrics['cost_per_1000']:.2f}")

    print("\n" + "=" * 70)


def plot_quality_comparison(results: Dict[str, Dict], output_path: str):
    """Create quality comparison plots.

    Args:
        results: Quality metrics by backend
        output_path: Path to save plot
    """

    backends = list(results.keys())
    if not backends:
        print("No results to plot")
        return

    # Collect metrics
    metrics_to_plot = ['fid', 'is_mean', 'tv_similarity']
    metric_labels = ['FID (lower better)', 'Inception Score', 'TV Similarity']

    fig, axes = plt.subplots(1, 3, figsize=(14, 5))

    colors = {
        'stable_diffusion': '#2196F3',
        'dalle': '#FF9800',
        'sd3.5': '#4CAF50',
        'gpt_image': '#9C27B0'
    }

    for ax, metric, label in zip(axes, metrics_to_plot, metric_labels):
        values = []
        backend_names = []

        for backend in backends:
            if metric in results[backend]:
                values.append(results[backend][metric])
                backend_names.append(backend)

        if values:
            x = np.arange(len(backend_names))
            bars = ax.bar(x, values, color=[colors.get(b, '#888888') for b in backend_names])
            ax.set_xticks(x)
            ax.set_xticklabels(backend_names, rotation=45, ha='right')
            ax.set_ylabel(label)
            ax.set_title(label.split('(')[0].strip())
            ax.grid(axis='y', alpha=0.3)

    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches='tight')
    print(f"Plot saved to: {output_path}")
    plt.close()


def main():
    parser = argparse.ArgumentParser(description="Analyze synthetic image quality")
    parser.add_argument(
        "--synthetic-dir",
        type=str,
        default="data/synthetic_images",
        help="Directory containing synthetic images"
    )
    parser.add_argument(
        "--real-dataset",
        type=str,
        default="CIFAR10",
        help="Real dataset name for comparison"
    )
    parser.add_argument(
        "--backends",
        type=str,
        default="stable_diffusion,dalle",
        help="Comma-separated list of backends to analyze"
    )
    parser.add_argument(
        "--metrics",
        type=str,
        default="fid,is,lpips",
        help="Comma-separated list of metrics to compute"
    )
    parser.add_argument(
        "--checkpoint-dir",
        type=str,
        default="checkpoints/ViT-B-32",
        help="Directory with model checkpoints"
    )
    parser.add_argument(
        "--output",
        type=str,
        default="synthetic_quality_comparison.pdf",
        help="Output path for visualization"
    )

    args = parser.parse_args()

    print("=" * 60)
    print("SYNTHETIC IMAGE QUALITY ANALYSIS")
    print("=" * 60)
    print(f"Synthetic directory: {args.synthetic_dir}")
    print(f"Real dataset: {args.real_dataset}")
    print(f"Backends: {args.backends}")
    print(f"Metrics: {args.metrics}")

    backends = args.backends.split(',')
    metrics = args.metrics.split(',')

    results = {}

    for backend in backends:
        print(f"\nAnalyzing {backend}...")
        results[backend] = {}

        # Get image statistics
        backend_dir = Path(args.synthetic_dir) / backend / args.real_dataset
        if backend_dir.exists():
            stats = compute_image_statistics(str(backend_dir))
            results[backend]['image_stats'] = stats
            print(f"  Found {stats.get('num_images', 0)} images")

            # Count per class
            counts = count_images_per_class(args.synthetic_dir, backend, args.real_dataset)
            results[backend]['class_counts'] = counts
        else:
            print(f"  Directory not found: {backend_dir}")
            results[backend]['image_stats'] = {'num_images': 0}

        # Load precomputed metrics if available
        tv_sim = load_task_vector_similarity(args.checkpoint_dir, backend)
        if tv_sim is not None:
            results[backend]['tv_similarity'] = tv_sim

        # Add cost estimates
        cost_estimates = {
            'stable_diffusion': 0.0,  # Free (local)
            'dalle': 40.0,  # $0.040 per image
            'sd3.5': 0.0,  # Free (local)
            'gpt_image': 50.0  # Estimate
        }
        results[backend]['cost_per_1000'] = cost_estimates.get(backend, 0.0)

    # Print report
    print_quality_report(results)

    # Generate plots
    print("\nGenerating visualizations...")
    plot_quality_comparison(results, args.output)

    # Save detailed results
    results_path = args.output.replace('.pdf', '_results.json')
    with open(results_path, 'w') as f:
        # Convert numpy types for JSON
        def convert(obj):
            if isinstance(obj, np.ndarray):
                return obj.tolist()
            elif isinstance(obj, (np.int64, np.int32)):
                return int(obj)
            elif isinstance(obj, (np.float64, np.float32)):
                return float(obj)
            return obj

        json_results = json.loads(json.dumps(results, default=convert))
        json.dump(json_results, f, indent=2)
    print(f"Results saved to: {results_path}")

    print("\n" + "=" * 60)
    print("Analysis complete!")
    print("=" * 60)


if __name__ == "__main__":
    main()
